---
- name: Install required packages for Alertmanager
  package:
    name: alertmanager
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'apt' and ansible_distribution in ['Debian', 'Ubuntu'] 
- name: Install required packages for Alertmanager
  package:
    name: prometheus-alertmanager
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'yum' and ansible_distribution in ['Amazon', 'CentOS', 'RedHat', 'Fedora']
- name: Create Alertmanager configuration directory
  file:
    path: /etc/alertmanager/
    state: directory

- name: Copy Alertmanager configuration file
  copy:
    src: alertmanager.yml
    dest: /etc/alertmanager/alertmanager.yml

- name: Start Alertmanager service and enable it on boot
  systemd:
    name: alertmanager
    state: started
    enabled: yes
