---
- name: Install required packages for Alertmanager
  package:
    name: "{{ ['unzip', 'tar'] }}"
    state: present
  when: ansible_pkg_mgr == 'apt'  # Ubuntu and Debian

- name: Install required packages for Alertmanager
  package:
    name: "{{ ['unzip', 'tar'] }}"
    state: present
  when: ansible_pkg_mgr == 'yum'  # CentOS, Amazon, Fedora, RedHat

- name: Download Alertmanager binary
  get_url:
    url: "{{ alertmanager_url }}"
    dest: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"

- name: Extract Alertmanager binary
  unarchive:
    src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    dest: "{{ alertmanager_install_dir }}"
    remote_src: yes
    creates: "{{ alertmanager_install_dir }}/alertmanager-{{ alertmanager_version }}"

- name: Rename Alertmanager binary
  command: mv "{{ alertmanager_install_dir }}/alertmanager-{{ alertmanager_version }}/alertmanager" "{{ alertmanager_install_dir }}/alertmanager"

- name: Create Alertmanager configuration directory
  file:
    path: "/etc/alertmanager/"
    state: directory

- name: Copy Alertmanager configuration file
  copy:
    src: "{{ alertmanager_config_src }}"
    dest: "{{ alertmanager_config_dest }}"

- name: Create Alertmanager service file
  template:
    src: alertmanager.service.j2
    dest: "{{ alertmanager_service_dest }}"
